version: '3'
services:
  nginx:
    platform: linux/arm64/v8
    image: nginx:latest
    container_name: dev-nginx
    volumes:
      - ./apps/server/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./apps/server/nginx/wait-for-it.sh:/wait-for-it.sh
      - ./apps/server/nginx/docker-entrypoint.production.sh:/docker-entrypoint.production.sh
    command: /bin/bash -c "chmod +x /docker-entrypoint.production.sh && /docker-entrypoint.production.sh"
    ports:
      - "80:80"
    depends_on:
      - dev-server
    links:
      - dev-server
    networks:
      - dev-dothis-network
  dev-server:
    container_name: api-server
    build:
      context: .
      dockerfile: Dockerfile.development
    env_file:
      - apps/server/development.env
    volumes:
      - ./package.json:/app/package.json
      - ./turbo.json:/app/turbo.json
      - ./pnpm-workspace.yaml:/app/pnpm-workspace.yaml
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml
      - ./.npmrc:/app/.npmrc
      - ./apps/server/package.json:/app/apps/server/package.json
      - ./apps/server:/app/apps/server
      - ./config:/app/config
      - ./packages:/app/packages
    ports:
      - "8080"
    restart: always
    networks:
      - dev-dothis-network
  db-mysql:
    platform: linux/arm64/v8
    container_name: dothis-mysql
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${DB_SCHEMA}
      - TZ=Asia/Seoul
    command:
      - --mysql-native-password=ON
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./apps/server/db/data/mysql:/var/lib/mysql
      - ./apps/server/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    networks:
      - dev-dothis-network
  cache-redis:
    platform: linux/arm64/v8
    container_name: dothis-redis
    image: redis:latest
    restart: always
    environment:
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_HOSTNAME=${REDIS_HOSTNAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - TZ=Asia/Seoul
    command: redis-server /usr/local/conf/redis.conf
    volumes:
      - ./apps/server/db/redis/data:/data
      - ./apps/server/db/redis/conf/redis.conf:/usr/local/conf/redis.conf
    ports:
      - 6379:6379
    networks:
      - dev-dothis-network
#  perf-test:
#    build: .
#    image: artilleryio/artillery:latest
#    platform: linux/arm64/v8
#    environment:
#      REDIS_PORT: dev-server:80
#      MAX_LATENCY: 1000
#      MIN_RPS: 200
#      TEST_CONFIG: |-
#        config:
#          target: "{{ $processEnvironment.TARGET_URL }}"
#          phases:
#            - duration: 1
#              arrivalRate: 1
#          defaults:
#            headers:
#              accept: application/json
#
#        scenarios:
#          - flow:
#              - get:
#                  url: "/v1/hits/daily/24%2C%2033%2C%2022%2C%2023%2C%208?search=%EC%84%9C%EC%9A%B8&related=%EB%8C%80%EA%B5%AC&from=2024-04-01&to=2024-04-10"
#              - get:
#                  url: "v1/hits/expectation/0%2C1%2C2%2C3%2C4?search=%EC%84%9C%EC%9A%B8&related=%EB%8C%80%EA%B5%AC&from=2024-04-01&to=2024-04-10"
#              - get:
#                  url: "v1/related-word/%EC%84%9C%EC%9A%B8/ranking"
networks:
  dev-dothis-network:

