x-defaults:
  &defaults
  init: true
  tty: true
  networks:
    - dev-dothis-network

services:
  nginx:
    platform: linux/arm64/v8
    image: nginx:latest
    container_name: dev-nginx
    volumes:
      - ./apps/server/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./apps/server/nginx/wait-for-it.sh:/wait-for-it.sh
      - ./apps/server/nginx/docker-entrypoint.production.sh:/docker-entrypoint.production.sh
    command: /bin/bash -c "chmod +x /docker-entrypoint.production.sh && /docker-entrypoint.production.sh"
    ports:
      - "80:80"
    depends_on:
      - dev-server
    links:
      - dev-server
    networks:
      - dev-dothis-network

  dev-server:
    <<: *defaults
    container_name: api-server
    command: pnpm dev:back-end
    ports:
      - "8080"
    build:
      args:
        APP: server
        START_COMMAND: dev
      context: .
      dockerfile: ./Dockerfile.dev
    env_file:
      - apps/server/development.env
    volumes:
      - ./apps/server:/app/apps/server
      - ./packages/dto:/app/packages/dto
      - /app/apps/server/node_modules
    restart: always
    networks:
      - dev-dothis-network

  db-mysql:
    platform: linux/arm64/v8
    container_name: dothis-mysql
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${DB_SCHEMA}
      - TZ=Asia/Seoul
    command:
      - --mysql-native-password=ON
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./apps/server/db/data/mysql:/var/lib/mysql
      - ./apps/server/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    networks:
      - dev-dothis-network

  cache-redis:
    platform: linux/arm64/v8
    container_name: dothis-redis
    image: redis:7.2-alpine
    restart: always
    environment:
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_HOSTNAME=${REDIS_HOSTNAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - TZ=Asia/Seoul
    command: redis-server /usr/local/conf/redis.conf
    volumes:
      - ./apps/server/db/redis/data:/data
      - ./apps/server/db/redis/conf/redis.conf:/usr/local/conf/redis.conf
    ports:
      - 6379:6379
    networks:
      - dev-dothis-network

networks:
  dev-dothis-network:
    driver: bridge
