version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: dev-nginx
    volumes:
      - ./apps/server/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./apps/server/nginx/wait-for-it.sh:/wait-for-it.sh
      - ./apps/server/nginx/docker-entrypoint.production.sh:/docker-entrypoint.production.sh
    command: /bin/bash -c "chmod +x /docker-entrypoint.production.sh && /docker-entrypoint.production.sh"
    ports:
      - "80:80"
    depends_on:
      - server
    links:
      - server
    networks:
      - dothis-network-prod
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-server
    env_file:
      - apps/server/production.env
    ports:
      - "8080"
    restart: always
    networks:
      - dothis-network-prod
  cache-redis:
    container_name: dothis-redis
    image: redis:latest
    restart: always
    env_file:
      - apps/server/production.env
    environment:
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_HOSTNAME=${REDIS_HOSTNAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - TZ=Asia/Seoul
    command: redis-server /usr/local/conf/redis.conf
    volumes:
      - ./apps/server/db/redis/data:/data
      - ./apps/server/db/redis/conf/redis.conf:/usr/local/conf/redis.conf
    ports:
      - 6379:6379
    networks:
      - dothis-network-prod

networks:
  dothis-network-prod: