version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/back-end
    overwrite: yes
file_exists_behavior: OVERWRITE

permissions:
  - object: /
    pattern: '**'
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: ./scripts/after-deploy.sh
      timeout: 180
      runas: root
