version: '3.8'

services:
  dothis-nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/wait-for-it.sh:/wait-for-it.sh
      - ./nginx/docker-entrypoint.production.sh:/docker-entrypoint.production.sh
    command: /bin/bash -c "chmod +x /docker-entrypoint.production.sh && /docker-entrypoint.production.sh"
    networks:
      - frontend
    depends_on:
      - external-sales-api
    ports:
      - "80:80"

  external-sales-api:
    image: 505558602960.dkr.ecr.ap-northeast-2.amazonaws.com/external-sales-api:latest
    networks:
      - frontend
    env_file:
      - production.env
    depends_on:
      - dothis-redis
    ports:
      - "8080"
    container_name: external-sales-api-server

networks:
  frontend: