name: CI-CD

on:
  pull_request:
    branches: [deploy]

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: build

  build:
    name: Build, Deploy to S3 Bucket
    runs-on: ubuntu-latest

    env:
      working-directory: ./

    strategy:
      matrix:
        node-version: [18.13.0]

    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
          run_install: false
          
      - name: install dev
        working-directory: ./
        run: |
            pnpm i --no-frozen-lockfile
            
      - name: create env file
        working-directory: ./apps/back-end
        run: |
          pwd
          touch production.env
          echo MYSQL_ROOT_USER=${{ secrets.MYSQL_ROOT_USER }} >> production.env
          echo MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }} >> production.env
          echo MYSQL_USER=${{ secrets.MYSQL_USER }} >> production.env
          echo MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} >> production.env
          echo DB_PORT=${{ secrets.DB_PORT }} >> production.env
          echo DB_HOST=${{ secrets.DB_HOST }} >> production.env
          echo DB_SCHEMA=${{ secrets.DB_SCHEMA }} >> production.env
          echo GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} >> production.env
          echo GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} >> production.env
          echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> production.env
          echo ACCESS_TOKEN_EXPIRESIN=${{ secrets.ACCESS_TOKEN_EXPIRESIN }} >> production.env
          echo REFRESH_TOKEN_EXPIRESIN=${{ secrets.REFRESH_TOKEN_EXPIRESIN }} >> production.env          
          cat production.env

      - name: build
        working-directory: ./
        run: |
         chmod +x pnpm run build:back-end

      - name: zip file
        working-directory: ./apps/back-end
        run: zip -r dothisBackEnd.zip ./dist ./scripts ./production.env ./appspec.yml ./package.json ./package-lock.json ./ecosystem.config.js ./tsconfig.json ./tsconfig.build.json

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        working-directory: ./apps/back-end
        run: aws s3 cp --region ap-northeast-2 ./dothisBackEnd.zip ${{ secrets.AWS_S3_BUCKET_NAME }}

      - name: deploy with AWS codeDeploy
        working-directory: ./apps/back-end
        run: aws deploy create-deployment
          --application-name github-action
          --deployment-config-name CodeDeployDefault.OneAtATime
          --deployment-group-name github-action-group
          --s3-location bucket=dothis,bundleType=zip,key=git-archive/dothisBackEnd.zip

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2022.3.0
